AliceO2Group/ReadoutCard

include/ReadoutCard/Parameters.h, include/ReadoutCard/Superpage.h, src/CommandLineUtilities/ProgramCleanup.cxx, src/CommandLineUtilities/ProgramDmaBench.cxx, src/Crorc/CrorcDmaChannel.cxx, src/Cru/CruDmaChannel.cxx, src/Cru/DataFormat.h, src/Dummy/DummyDmaChannel.cxx, src/Example.cxx, src/Parameters.cxx, test/TestSuperpageQueue.cxx
Assigned to @sy-c as it includes interface changes.
=> ORC-103/superpage-flags

CMakeLists.txt
=> Fix the build on CC7 with PDA

cmake/FindInfoLogger.cmake
This is needed for alisw/alidist#1516 to work.
=> Use correct header for detection

CMakeLists.txt, cmake/ReadoutCardConfig.cmake.in, include/ReadoutCard/CardConfigurator.h, src/CardConfigurator.cxx, src/CommandLineUtilities/ProgramConfig.cxx, src/ExceptionInternal.cxx, src/ExceptionInternal.h
Have to wait for the following before merging.
- https://github.com/AliceO2Group/Configuration/pull/49
- https://github.com/alisw/alidist/pull/1870
=> [roc-config] Use AliceO2 configuration library

README.md, src/CommandLineUtilities/ProgramConfig.cxx, src/FirmwareChecker.cxx
=> Handle the ONU address argument as an int and update compatible FW versions

src/Cru/CruBar.h, src/Cru/CruDmaChannel.cxx
=> [cru] Don't push superpages to disabled links

src/CommandLineUtilities/ProgramMetrics.cxx, src/CommandLineUtilities/ProgramPacketMonitor.cxx, src/CommandLineUtilities/ProgramStatus.cxx, src/Utilities/Util.h
=> [roc-{metrics,pkt-monitor}] Add json output + packet rate

CMakeLists.txt, README.md, cmake/ReadoutCardConfig.cmake.in, include/ReadoutCard/CardDescriptor.h, src/CommandLineUtilities/Program.h, src/CommandLineUtilities/ProgramMetrics.cxx, src/CommandLineUtilities/ProgramStatus.cxx, src/Dummy/DummyDmaChannel.cxx, src/Pda/Util.h, src/RocPciDevice.cxx, src/RocPciDevice.h
=> Use the monitoring library for roc tools

README.md, src/FirmwareChecker.cxx
=> [fw-check] Add CRORC v2.6.1 to fw compatibility list

README.md, src/CommandLineUtilities/ProgramMetrics.cxx, src/CommandLineUtilities/ProgramStatus.cxx, src/Crorc/Common.h, src/Cru/Common.h
=> [mon] Improve monitoring interface

src/Crorc/Constants.h, src/Crorc/CrorcBar.cxx
=> ORC-338: [crorc] Fix CRORC QSFP status addressing

README.md, cru_template.cfg, include/ReadoutCard/Cru.h, include/ReadoutCard/ParameterTypes/GbtMux.h, src/CommandLineUtilities/ProgramConfig.cxx, src/Crorc/Constants.h, src/Crorc/CrorcBar.cxx, src/Cru/Gbt.cxx, src/ParameterTypes/GbtMux.cxx
=> ORC-335: Add TTCUP gbt mux option

src/Cru/CruBar.cxx
=> ORC-341: [ctp-emu] Update bunch crossing defaults

src/Cru/PatternPlayer.cxx
=> [pat-player] Set the patterns even when empty

README.md, src/Crorc/Constants.h, src/Crorc/CrorcBar.cxx, src/FirmwareChecker.cxx
=> CRORC FW v2.7.0 support

src/Crorc/CrorcBar.cxx, src/Crorc/CrorcBar.h, src/Crorc/CrorcDmaChannel.cxx
=> [crorc] Flush superpages on DMA stop

src/Crorc/CrorcDmaChannel.cxx
=> [crorc] Reset CRORC on DMA start

src/Cru/CruBar.cxx, src/Cru/Gbt.cxx, src/Cru/Gbt.h
=> [roc-config] Reset the GBT FIFO on config end

README.md, cru_template.cfg, include/ReadoutCard/Cru.h, include/ReadoutCard/ParameterTypes/GbtMux.h, src/CommandLineUtilities/ProgramConfig.cxx, src/Cru/Gbt.cxx, src/ParameterTypes/GbtMux.cxx
=> [cru] Add GBT MUX UL option

README.md, src/CommandLineUtilities/ProgramStatus.cxx
=> [roc-status] Report ONU sticky bit as int for monitoring

src/CommandLineUtilities/ProgramCleanup.cxx
=> [cleanup] Add CRORC FIFO shm files

src/CommandLineUtilities/ProgramStatus.cxx, src/Cru/Ttc.cxx
=> [onu] Report correct onu sticky status

include/ReadoutCard/InterprocessLock.h, src/Cru/CruBar.cxx, src/Cru/CruBar.h, src/Cru/Ttc.cxx, src/Cru/Ttc.h
=> [i2c] Lock around I2C operations to avoid interference

src/Cru/Gbt.cxx
=> [cru] Reset TX and RX FIFO on config

CMakeLists.txt, include/ReadoutCard/DmaChannelInterface.h, include/ReadoutCard/Logger.h, src/BarInterfaceBase.cxx, src/BarInterfaceBase.h, src/CardConfigurator.cxx, src/CommandLineUtilities/Program.h, src/CommandLineUtilities/ProgramConfig.cxx, src/CommandLineUtilities/ProgramCtpEmulator.cxx, src/CommandLineUtilities/ProgramDmaBench.cxx, src/CommandLineUtilities/ProgramMetrics.cxx, src/CommandLineUtilities/ProgramPacketMonitor.cxx, src/CommandLineUtilities/ProgramPatternPlayer.cxx, src/CommandLineUtilities/ProgramSiuStatus.cxx, src/CommandLineUtilities/ProgramTriggerMonitor.cxx, src/Crorc/CrorcBar.cxx, src/Crorc/CrorcDmaChannel.cxx, src/Cru/CruBar.cxx, src/Cru/CruDmaChannel.cxx, src/Cru/Ttc.cxx, src/DmaChannelBase.cxx, src/DmaChannelBase.h, src/DmaChannelPdaBase.cxx, src/Dummy/DummyDmaChannel.cxx, src/Logger.cxx, src/Pda/PdaDmaBuffer.cxx, src/Pda/Util.h
=> [roc] Improve InfoLogger facility

src/CommandLineUtilities/ProgramConfig.cxx
=> Fix config generation bug

src/Cru/Constants.h, src/Cru/CruBar.cxx, src/Cru/CruBar.h, src/Cru/cru_constants_populate.py, src/Cru/pack_cru_core.vhd
=> [cru] Set the system id for the virtual links

src/CommandLineUtilities/ProgramStatus.cxx, src/Crorc/CrorcBar.cxx, src/Crorc/CrorcBar.h, src/Cru/CruBar.cxx, test/TestParameters.cxx
=> [status] Add option to specify links reported

src/CommandLineUtilities/ProgramConfig.cxx, src/CommandLineUtilities/ProgramListCards.cxx, src/CommandLineUtilities/ProgramSiuStatus.cxx
=> [roc] CLI tools should throw the errors they catch

src/CardConfigurator.cxx, src/CommandLineUtilities/ProgramConfig.cxx, src/Utilities/Enum.h
=> [roc-config] Improve user feedback for invalid options

CMakeLists.txt, src/CommandLineUtilities/ProgramUserLogic.cxx, src/Cru/Common.h, src/Cru/Constants.h, src/Cru/CruBar.cxx, src/Cru/CruBar.h, src/Cru/cru_constants_populate.py
=> [ul] Introduce tool to control the dummy UL

src/Crorc/CrorcBar.cxx
=> [crorc] Don't assert link on INTERNAL or DIU

src/Logger.cxx
=> [roc] Don't log 'facility set' messages

include/ReadoutCard/Cru.h, src/Cru/cru_constants_populate.py, src/Cru/pack_cru_core.vhd
This reverts commit 6ab776e940e437c00757f15da9db3a2cfa04a3e5.
=> Temporarily revert "[roc] Update SC registers"

src/CommandLineUtilities/ProgramCleanup.cxx
=> [cleanup] Add flag to skip PDA module removal

src/CommandLineUtilities/ProgramDmaBench.cxx
=> [bench-dma] Improve TF checks

src/CommandLineUtilities/ProgramTriggerMonitor.cxx, src/Cru/Common.h, src/Cru/Constants.h, src/Cru/CruBar.cxx, src/Cru/Ttc.cxx, src/Cru/Ttc.h, src/Cru/pack_cru_core.vhd
=> [roc-trg-monitor] Add TOF trigger

README.md, src/CommandLineUtilities/ProgramStatus.cxx, src/Cru/Common.h, src/Cru/Constants.h, src/Cru/CruBar.cxx, src/Cru/I2c.cxx, src/Cru/I2c.h, src/Cru/Ttc.cxx, src/Cru/Ttc.h, src/Cru/cru_constants_populate.py
=> [roc-status] Add PON RX power

include/ReadoutCard/DmaChannelInterface.h, src/Crorc/CrorcDmaChannel.cxx, src/Crorc/CrorcDmaChannel.h, src/Cru/Constants.h, src/Cru/CruBar.cxx, src/Cru/CruBar.h, src/Cru/CruDmaChannel.cxx, src/Cru/CruDmaChannel.h
=> [dma-channel] Interface for Superpage FIFO empty counters

src/CommandLineUtilities/ProgramStatus.cxx
=> [status] Fix fec uint8_t counter output

src/CommandLineUtilities/ProgramCleanup.cxx
=> [roc-cleanup] Ignore system() return value

src/CommandLineUtilities/ProgramBarStress.cxx, src/CommandLineUtilities/ProgramCleanup.cxx, src/CommandLineUtilities/ProgramConfig.cxx, src/CommandLineUtilities/ProgramCtpEmulator.cxx, src/CommandLineUtilities/ProgramDmaBench.cxx, src/CommandLineUtilities/ProgramFirmwareCheck.cxx, src/CommandLineUtilities/ProgramFlash.cxx, src/CommandLineUtilities/ProgramFlashRead.cxx, src/CommandLineUtilities/ProgramListCards.cxx, src/CommandLineUtilities/ProgramMetrics.cxx, src/CommandLineUtilities/ProgramPacketMonitor.cxx, src/CommandLineUtilities/ProgramPatternPlayer.cxx, src/CommandLineUtilities/ProgramRegisterModify.cxx, src/CommandLineUtilities/ProgramRegisterRead.cxx, src/CommandLineUtilities/ProgramRegisterReadRange.cxx, src/CommandLineUtilities/ProgramRegisterWrite.cxx, src/CommandLineUtilities/ProgramReset.cxx, src/CommandLineUtilities/ProgramSiuStatus.cxx, src/CommandLineUtilities/ProgramStatus.cxx, src/CommandLineUtilities/ProgramTriggerMonitor.cxx, src/CommandLineUtilities/ProgramUserLogic.cxx
=> [roc] Update with o2- prefixed names in help dialogs

src/Cru/CruBar.cxx, src/Cru/CruBar.h, src/Cru/CruDmaChannel.cxx, src/Cru/DatapathWrapper.cxx, src/Cru/DatapathWrapper.h
=> [cru/dma] Data taking links should be enabled and up

src/CommandLineUtilities/ProgramStatus.cxx, src/Cru/Constants.h, src/Cru/CruBar.cxx, src/Cru/CruBar.h, src/Cru/Ttc.cxx, src/Cru/Ttc.h
=> [roc-status] Use different ONU sticky bit for monitoring and cli invocations

README.md, cru_template.cfg, src/CardConfigurator.cxx, src/CommandLineUtilities/ProgramStatus.cxx
=> [config] ONU address as dec instead of hex

src/Cru/Constants.h, src/Cru/CruBar.cxx, src/Cru/CruBar.h, src/Cru/CruDmaChannel.cxx, src/Cru/CruDmaChannel.h
=> [cru] Dynamically get FW SP FIFO size
